apps/cobranza/creditos/urls.py
from django.urls import path

from apps.cobranza.creditos.views import credit_detail

app_name = 'creditos'

urlpatterns = [
    path('credito/<slug:empresa>/<slug:credito>/', credit_detail, name='credit_detail')
]

apps/cobranza/dashboards/urls.py
from django.urls import path

from apps.cobranza.dashboards.views import dashboard_manager

app_name = 'dashboard'

urlpatterns = [
    path('manager', dashboard_manager, name='dashboardManager')
]

config/urls.py
# from django.contrib import admin
from django.urls import path, include
from apps.user.views import LoginFormView, lista
from django.conf import settings

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('', LoginFormView.as_view(), name='login'),
    path('creditos/', include('apps.cobranza.creditos.urls')),
    path('dashboards/', include('apps.cobranza.dashboards.urls')),
]

apps/cobranza/acciones/models.py
from django.db import models

# Create your models here.

apps/cobranza/creditos/models.py
from django.db import models
from django.core import checks, exceptions, validators


class Creditos(models.Model):
    referencia = models.CharField(max_length=255, blank=True, null=True)
    montoentregado = models.DecimalField(max_digits=20, decimal_places=2, blank=True, null=True)
    fechaactivacion = models.DateField(blank=True, null=True)
    credito = models.CharField(max_length=50, blank=True, null=True)
    idproducto = models.IntegerField()
    cliente = models.CharField(max_length=50, blank=True, null=True)
    producto = models.CharField(max_length=255, blank=True, null=True)
    producto_corto = models.CharField(max_length=255, blank=True, null=True)
    saldo = models.DecimalField(max_digits=20, decimal_places=2, blank=True, null=True)
    montovencido = models.DecimalField(max_digits=20, decimal_places=2, blank=True, null=True)
    costos_asociados = models.DecimalField(max_digits=20, decimal_places=2, blank=True, null=True)
    impuesto = models.DecimalField(max_digits=20, decimal_places=2, blank=True, null=True)
    impuesto_total = models.DecimalField(max_digits=20, decimal_places=2, blank=True, null=True)
    iopend = models.DecimalField(max_digits=20, decimal_places=2, blank=True, null=True)
    vence = models.DateField(blank=True, null=True)
    abono = models.DecimalField(max_digits=20, decimal_places=2, blank=True, null=True)
    diasmora = models.IntegerField(blank=True, null=True)
    interes_total = models.DecimalField(max_digits=20, decimal_places=2, blank=True, null=True)
    cuenta_2001 = models.CharField(max_length=50, blank=True, null=True)
    cuenta_respiro = models.CharField(max_length=50, blank=True, null=True)
    empresa = models.CharField(max_length=2, blank=True, null=True)
    clave = models.CharField(max_length=50, blank=True, null=False, primary_key = True)
    cantidad_creditos = models.IntegerField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'creditos'

    def _check_primary_key(self):
        if self.primary_key:
            return [
                checks.Error(
                    "AutoFieldNonPrimary must not set primary_key=True. bla bla bla",
                    obj=self,
                    id="fields.E100",
                )
            ]
        else:
            return []

class Gestores(models.Model):
    idusuario = models.CharField(max_length=60, blank=True, null=True)
    credito = models.CharField(max_length=60, blank=True, null=True)
    cliente = models.CharField(max_length=60, blank=True, null=True)
    empresa = models.CharField(max_length=10, blank=True, null=True)
    fecha = models.DateField()
    id = models.IntegerField(primary_key=True)

    class Meta:
        managed = False
        db_table = 'gestores'

apps/cobranza/dashboards/models.py
from django.db import models

# Create your models here.

apps/cobranza/depositos/models.py
from django.db import models

# Create your models here.

apps/cobranza/rutas/models.py
from django.db import models

# Create your models here.

apps/user/models.py
from django.db import models

# Create your models here.
'''
class Usuarios(models.Model):
    iduser = models.AutoField(db_column='idUser', primary_key=True)  # Field name made lowercase.
    nombre = models.CharField(max_length=80, blank=True, null=True)
    email = models.CharField(max_length=80, blank=True, null=True)
    password = models.CharField(max_length=80, blank=True, null=True)
    idrol = models.IntegerField(db_column='idRol', blank=True, null=True)  # Field name made lowercase.
    created_at = models.DateTimeField(blank=True, null=True)
    updated_at = models.DateTimeField(blank=True, null=True)
    rango_min = models.IntegerField(blank=True, null=True)
    rango_max = models.IntegerField(blank=True, null=True)
    status = models.BooleanField()
    username = models.CharField(max_length=50, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'Usuarios'
'''

class Usuarios(models.Model):
    password = models.CharField(max_length=128)
    last_login = models.DateTimeField(blank=True, null=True)
    is_superuser = models.BooleanField()
    username = models.CharField(unique=True, max_length=150)
    first_name = models.CharField(max_length=150)
    last_name = models.CharField(max_length=150)
    email = models.CharField(max_length=254)
    is_staff = models.BooleanField()
    is_active = models.BooleanField()
    date_joined = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'auth_user'

djangoFi/models.py
from django.db import models

# Create your models here.

apps/cobranza/acciones/views.py
from django.shortcuts import render

# Create your views here.

apps/cobranza/creditos/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required

from apps.cobranza.creditos.models import Creditos


class CreditDetail(LoginRequiredMixin, TemplateView):
    template_name = 'credit.html'
    model = Creditos

    @method_decorator(csrf_exempt)
    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super().dispatch(request, *args, **kwargs)

    def get_object(self, queryset=None):
        return self.request.user

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Detalle credito'
        context['entity'] = 'Credito'
        return context


@login_required
def credit_detail(request, empresa, credito):
    credit = Creditos.objects.raw('select * from creditos '
                                  'inner join info_cliente on creditos.cliente = info_cliente.cliente and creditos.empresa = info_cliente.empresa WHERE creditos.empresa = %s and creditos.credito = %s', [empresa, credito])[:1]
    context = {
        'credit': credit[0],
        'title': 'Detalle credito',
        'entity': 'Credito',
    }
    return render(request, 'credit.html', context)

apps/cobranza/dashboards/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from apps.cobranza.creditos.models import Gestores


@login_required
def dashboard_manager(request):
    credits = Gestores.objects.filter(idusuario = 'aperez')

    context = {
        'credits': credits,
        'title': 'Dashboard ' + request.user.username,
        'entity': 'Credito',
    }
    return render(request, 'dashboardManager.html', context)

apps/cobranza/depositos/views.py
from django.shortcuts import render

# Create your views here.

apps/cobranza/rutas/views.py
from django.shortcuts import render

# Create your views here.

apps/user/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LoginView
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.utils.decorators import method_decorator

from apps.user.models import Usuarios


class LoginFormView(LoginView):
    template_name = 'login.html'

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('dashboards/manager')
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(** kwargs)
        context['title'] = 'Iniciar Sesión'
        return context


def lista(request):

    data = {
        'name': 'Hola',
        'usuarios': Usuarios.objects.all()
    }
    return render(request, 'usuarios/prueba.html', data)

djangoFi/views.py
from django.shortcuts import render

# Create your views here.

apps/user/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>                        
        <title>Boooyassss - Login</title>
        
        <!-- META SECTION -->
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        
        <link rel="shortcut icon" href="favicon.ico" type="image/x-icon">
        <link rel="icon" href="favicon.ico" type="image/x-icon">
        <!-- END META SECTION -->
        <!-- CSS INCLUDE -->
        <script type="text/javascript" src="{% static 'js/vendor/sweetalert/sweetalert2.all.min.js' %}"></script>
        <link rel="stylesheet" href="{% static 'css/styles.css' %}">
        <!-- EOF CSS INCLUDE -->
    </head>
    <body>        
        
        <!-- APP WRAPPER -->
        <div class="app">

            <!-- START APP CONTAINER -->
            <div class="app-container">
                
                <div class="app-login-box">                                        
                    <div><img src="{% static '\img\Logo-Financiera.png' %}" alt="Financiera Sustentable"></div>
                    <div class="app-login-box-container">
                        <form action="" method="post">
                            {% csrf_token %}
                            <div class="form-group">
                                <input type="text" class="form-control" name="username" placeholder="Usuario">
                            </div>
                            <div class="form-group">
                                <input type="password" class="form-control" name="password" placeholder="Password">
                            </div>
                            <div class="form-group">

                                <div class="row">
                                    <div class="col-md-12 col-xs-12">
                                        <button class="btn btn-success btn-block">Ingresar</button>
                                    </div>
                                </div>
                                
                            </div>
                        </form>
                    </div>
                </div>
                                
            </div>
            <!-- END APP CONTAINER -->

           
        </div>        
        <!-- END APP WRAPPER -->                        
        <!-- IMPORTANT SCRIPTS -->
        <script type="text/javascript" src="{% static 'js/vendor/jquery/jquery.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/vendor/jquery/jquery-migrate.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/vendor/jquery/jquery-ui.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/vendor/bootstrap/bootstrap.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/vendor/moment/moment.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/vendor/customscrollbar/jquery.mCustomScrollbar.min.js' %}"></script>
        <!-- END IMPORTANT SCRIPTS -->
        <!-- APP SCRIPTS -->
        <script type="text/javascript" src="{% static 'js/app.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/app_plugins.js' %}"></script>
        <!-- END APP SCRIPTS -->
        <script type="application/javascript">
            {% if form.errors %}
                var errors = '';
                {% for field in form %}
                    {% for error in field.errors %}
                        errors += '{{ error }}\n';
                    {% endfor %}
                {% endfor %}
                {% for error in form.non_field_errors %}
                    errors += '{{ error }}\n';
                {% endfor %}
                Swal.fire({
                    title: 'Error!',
                    text: errors,
                    icon: 'error'
                });
            {% endif %}
        </script>
    </body>
</html>

templates/includes/footer.html
{% load static %}

            <!-- START APP FOOTER -->
            <div class="app-footer app-footer-default" id="footer">
                <div class="app-footer-line">
                    <div class="copyright">&copy; 2016-2017 Boooya. All right reserved in the Ukraine and other countries.</div>
                    <div class="pull-right">
                        <ul class="list-inline">
                            <li><a href="#">About</a></li>
                            <li><a href="#">Help</a></li>
                            <li><a href="#">Community</a></li>
                            <li><a href="#">Contacts</a></li>
                        </ul>
                    </div>
                </div>
            </div>
            <!-- END APP FOOTER -->

templates/includes/head.html
{% load static %}
<!-- START APP HEADER -->
                    <div class="app-header app-header-design-default">
                        <ul class="app-header-buttons">
                            <li class="visible-mobile"><a href="#" class="btn btn-link btn-icon" data-sidebar-toggle=".app-sidebar.dir-left"><span class="icon-menu"></span></a></li>
                            <li class="hidden-mobile"><a href="#" class="btn btn-link btn-icon" data-sidebar-minimize=".app-sidebar.dir-left"><span class="icon-menu"></span></a></li>
                        </ul>
                        <form class="app-header-search" action="" method="post">
                            <input type="text" name="keyword" placeholder="Search">
                        </form>

                        <ul class="app-header-buttons pull-right">
                            <li>
                                <div class="contact contact-rounded contact-bordered contact-lg contact-ps-controls hidden-xs">
                                    <div class="contact-container">
                                        <a href="#">{{  request.user.username }}</a>
                                        <span>{{ request.user.email }}</span>
                                    </div>
                                </div>
                            </li>
                            <li>
                                <div class="dropdown">
                                    <button class="btn btn-default btn-icon btn-informer" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true"><span class="icon-alarm"></span><span class="informer informer-danger informer-sm informer-square">+3</span></button>
                                    <ul class="dropdown-menu dropdown-form dropdown-left dropdown-form-wide">
                                        <li class="padding-0">

                                            <div class="app-heading title-only app-heading-bordered-bottom">
                                                <div class="icon">
                                                    <span class="icon-text-align-left"></span>
                                                </div>
                                                <div class="title">
                                                    <h2>Notifications</h2>
                                                </div>
                                                <div class="heading-elements">
                                                    <a href="#" class="btn btn-default btn-icon"><span class="icon-sync"></span></a>
                                                </div>
                                            </div>

                                            <div class="app-timeline scroll app-timeline-simple text-sm" style="height: 240px;">

                                                <div class="app-timeline-item">
                                                    <div class="dot dot-primary"></div>
                                                    <div class="content">
                                                        <div class="title margin-bottom-0"><a href="#">Jessie Franklin</a> uploaded new file <strong>844_jswork.pdf</strong></div>
                                                    </div>
                                                </div>

                                                <div class="app-timeline-item">
                                                    <div class="dot dot-warning"></div>
                                                    <div class="content">
                                                        <div class="title margin-bottom-0"><a href="#">Taylor Watson</a> changed work status <strong>PSD Dashboard</strong></div>
                                                    </div>
                                                </div>

                                                <div class="app-timeline-item">
                                                    <div class="dot dot-success"></div>
                                                    <div class="content">
                                                        <div class="title margin-bottom-0"><a href="#">Dmitry Ivaniuk</a> approved project <strong>Boooya</strong></div>
                                                    </div>
                                                </div>

                                                <div class="app-timeline-item">
                                                    <div class="dot dot-success"></div>
                                                    <div class="content">
                                                        <div class="title margin-bottom-0"><a href="#">Boris Shaw</a> finished work on <strong>Boooya</strong></div>
                                                    </div>
                                                </div>

                                                <div class="app-timeline-item">
                                                    <div class="dot dot-danger"></div>
                                                    <div class="content">
                                                        <div class="title margin-bottom-0"><a href="#">Jasmine Voyer</a> declined order <strong>Project 155</strong></div>
                                                    </div>
                                                </div>

                                            </div>

                                        </li>
                                        <li class="padding-top-0">
                                            <button class="btn btn-block btn-link">Preview All</button>
                                        </li>
                                    </ul>
                                </div>
                            </li>
                            <li>
                                <a href="pages-login.html" class="btn btn-default btn-icon"><span class="icon-power-switch"></span></a>
                            </li>
                        </ul>
                    </div>
                    <!-- END APP HEADER  -->

templates/includes/js.html
{% load static %}
<!-- IMPORTANT SCRIPTS -->
        <script type="text/javascript" src="{% static 'js/vendor/jquery/jquery.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/vendor/jquery/jquery-migrate.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/vendor/jquery/jquery-ui.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/vendor/bootstrap/bootstrap.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/vendor/moment/moment.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/vendor/customscrollbar/jquery.mCustomScrollbar.min.js' %}"></script>
        <!-- END IMPORTANT SCRIPTS -->
        <!-- THIS PAGE SCRIPTS -->
        <script type="text/javascript" src="{% static 'js/vendor/bootstrap-datetimepicker/bootstrap-datetimepicker.js' %}"></script>

        <script type="text/javascript" src="{% static 'js/vendor/jvectormap/jquery-jvectormap.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/vendor/jvectormap/jquery-jvectormap-world-mill-en.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/vendor/jvectormap/jquery-jvectormap-us-aea-en.js' %}"></script>

        <script type="text/javascript" src="{% static 'js/vendor/rickshaw/d3.v3.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/vendor/rickshaw/rickshaw.min.js' %}"></script>
        <!-- END THIS PAGE SCRIPTS -->
        <!-- APP SCRIPTS -->
        <script type="text/javascript" src="{% static 'js/app.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/app_plugins.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/app_demo.js' %}"></script>
        <!-- END APP SCRIPTS -->
        <script type="text/javascript" src="{% static 'js/app_demo_dashboard.js' %}"></script>

        <script type="text/javascript">
            $(function(){
                $(".block-refresh-example").on("click",function(){
                    var block = $(this).data("block");
                    app.block.loading.start("#"+block);
                    setTimeout(function(){
                        app.block.loading.finish("#"+block);
                    },3000);
                });
            });
        </script>

templates/includes/nav.html
{% load static %}
                <!-- START SIDEBAR -->
                <div class="app-sidebar app-navigation app-navigation-fixed scroll app-navigation-style-default app-navigation-open-hover dir-left" data-type="close-other" data-minimized="minimized">
                    <a href="index.html" class="app-navigation-logo">
                    </a>
                    <nav>
                        <ul>
                            <li class="title">Cobranza</li>
                            <li>
                                <a href="{% url 'creditos:credit_detail' 'FS' '1-3200-2145' %}"><span class="nav-icon-hexa">In</span> Inicio</a>
                            </li>
                            <li>
                                <a href="{% url 'dashboard:dashboardManager' %}"><span class="nav-icon-hexa">Ds</span> DASHBOARD </a>
                            </li>
                        </ul>
                    </nav>
                </div>
                <!-- END SIDEBAR -->